<?php

return [
    'patterns' => [
        'ssn' => '/\b\d{3}[-\s]?\d{2}[-\s]?\d{4}\b/',
        'mrn' => [
            '/\bMRN[:\s#]*\d{4,15}\b/i',
            '/\bMedical Record[:\s#]*\d{4,15}\b/i',
            '/\bPatient ID[:\s#]*\d{4,15}\b/i',
            '/\bChart[:\s#]*\d{4,15}\b/i',
            '/\bAcct[:\s#]*\d{4,15}\b/i',
            '/\bCase[:\s#]*\d{4,15}\b/i',
            '/\bΗΝ[:\-\s#]*\d{5,12}\b/ui',
            '/\bΑΜ[:\-\s#]*\d{5,12}\b/ui',
            '/\bΑΜΚΑ[:\-\s#]*\d{9,11}\b/ui',
            '/\bΑΡ\.?\s*ΜΗΤ\.?[:\-\s#]*\d{5,12}\b/ui',
            '/\bPat\.?[-\s]?Nr\.?[:\-\s#]*\d{5,15}\b/i',
            '/\bFallnummer[:\-\s#]*\d{5,15}\b/i',
            '/\bNIP[:\-\s#]*[0-9A-Z]{10,15}\b/i',
            '/\bNSS[:\-\s#]*\d{13,15}\b/i',
            '/\bINE[:\-\s#]*\d{9,12}\b/i',
            '/\bNHC[:\-\s#]*\d{6,15}\b/i',
            '/\bCIP[:\-\s#]*[A-Z]{4}\d{10,14}\b/i',
            '/\bNHS[:\-\s#]*\d{3}[-\s]?\d{3}[-\s]?\d{4}\b/i',
            '/\bHospital No\.?[:\-\s#]*\d{5,15}\b/i',
            '/\bCF[:\-\s#]*[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]\b/i',
            '/\bCodice Fiscale[:\-\s#]*[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]\b/i',
            '/\bSDO[:\-\s#]*\d{6,12}\b/i',
            '/\bBSN[:\-\s#]*\d{8,9}\b/i',
            '/\bAHV[:\-\s#]*\d{3}\.\d{4}\.\d{4}\.\d{2}\b/i',
            '/\bSVNR[:\-\s#]*\d{10}\b/i',
            '/\bCPR[:\-\s#]*\d{6}[-]?\d{4}\b/i',
            '/\bHetu[:\-\s#]*\d{6}[-+A]?\d{3}[A-Z]?\b/i',
            '/\bPESEL[:\-\s#]*\d{11}\b/i',
            '/\bRČ[:\-\s#]*\d{6}\/?\d{3,4}\b/iu',
            '/\b[A-Za-zΑ-Ωα-ω]{1,4}[:\-\s]*\d{6,10}\b/ui',
        ],
        'phone' => [
            '/\b\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/',
            '/\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b/',
            '/\+1[-.\s]?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/',
            '/\bphone[:\s]*\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/i',
            '/\bfax[:\s]*\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/i',
            '/\bcell[:\s]*\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b/i',
        ],
        'email' => '/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/',
        'ip_address' => '/\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/',
        'url' => '/\bhttps?:\/\/[^\s]+/i',
        'dates' => [
            '/\b(0?[1-9]|1[0-2])\/(0?[1-9]|[12]\d|3[01])\/(\d{4})\b/' => 'mdy_full',
            '/\b(0?[1-9]|1[0-2])\/(0?[1-9]|[12]\d|3[01])\/(\d{2})\b/' => 'mdy_short',
            '/\b(\d{4})-(0?[1-9]|1[0-2])-(0?[1-9]|[12]\d|3[01])\b/' => 'iso',
            '/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(0?[1-9]|[12]\d|3[01]),?\s+(\d{4})\b/i' => 'full_month',
            '/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\.?\s+(0?[1-9]|[12]\d|3[01]),?\s+(\d{4})\b/i' => 'abbrev_month',
            '/\bDOB[:\s]*(0?[1-9]|1[0-2])\/(0?[1-9]|[12]\d|3[01])\/(\d{2,4})\b/i' => 'dob',
            '/\bborn\s+(0?[1-9]|1[0-2])\/(0?[1-9]|[12]\d|3[01])\/(\d{2,4})\b/i' => 'born',
            '/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{4}\b/i' => 'month_year',
            '/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\.?\s+\d{4}\b/i' => 'month_year_abbrev',
            '/\b(Q[1-4]|first quarter|second quarter|third quarter|fourth quarter)\s+\d{4}\b/i' => 'quarter_year',
            '/\b(0?[1-9]|[12]\d|3[01])\/(0?[1-9]|1[0-2])\/(\d{4})\b/' => 'dmy_full',
            '/\b(0?[1-9]|[12]\d|3[01])\/(0?[1-9]|1[0-2])\/(\d{2})\b/' => 'dmy_short',
            '/\b(0?[1-9]|[12]\d|3[01])\.(0?[1-9]|1[0-2])\.(\d{4})\b/' => 'dmy_dot_full',
            '/\b(0?[1-9]|[12]\d|3[01])\.(0?[1-9]|1[0-2])\.(\d{2})\b/' => 'dmy_dot_short',
            '/\b(0?[1-9]|[12]\d|3[01])-(0?[1-9]|1[0-2])-(\d{4})\b/' => 'dmy_dash_full',
            '/\b(0?[1-9]|[12]\d|3[01])-(0?[1-9]|1[0-2])-(\d{2})\b/' => 'dmy_dash_short',
        ],
        'ages_over_90' => [
            '/\b(9[0-9]|1[0-9]{2})[-\s]*(year[-\s]*old|yo|y\.o\.|years[-\s]*old|yr[-\s]*old)\b/i',
            '/\b(age|aged)[:\s]*(9[0-9]|1[0-9]{2})\b/i',
        ],
        'device_identifiers' => [
            '/\bIMEI[:\s]*\d{15,17}\b/i',
            '/\bSerial[:\s#]*[A-Z0-9]{8,20}\b/i',
            '/\bMAC[:\s]*([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}\b/i',
            '/\bDevice ID[:\s]*[A-Z0-9-]{8,36}\b/i',
        ],
        'vehicle_identifiers' => [
            '/\bVIN[:\s#]*[A-HJ-NPR-Z0-9]{17}\b/i',
            '/\bLicense Plate[:\s#]*[A-Z0-9]{2,8}\b/i',
            '/\bPlate[:\s#]*[A-Z]{1,3}[-\s]?\d{3,4}[-\s]?[A-Z]{0,3}\b/i',
            '/\bVehicle ID[:\s#]*[A-Z0-9]{8,20}\b/i',
        ],
        'biometric_descriptors' => [
            '/\b(fingerprint|retina scan|iris scan|voice print|facial recognition)\s*(id|data|record)?[:\s#]*[A-Z0-9-]{4,30}\b/i',
            '/\bbiometric[:\s]*(id|data|record)?[:\s#]*[A-Z0-9-]{4,30}\b/i',
            '/\bDNA\s*(sample|profile|id)?[:\s#]*[A-Z0-9-]{4,30}\b/i',
        ],
        'license_numbers' => [
            '/\bDL[:\s#]*[A-Z]?\d{6,12}\b/i',
            '/\bDriver\'?s?\s*License[:\s#]*[A-Z0-9]{6,15}\b/i',
            '/\bLicense[:\s#]*[A-Z]{1,2}\d{6,10}\b/i',
            '/\bDEA[:\s#]*[A-Z]{2}\d{7}\b/i',
            '/\bNPI[:\s#]*\d{10}\b/i',
        ],
        'account_numbers' => [
            '/\bAccount[:\s#]*\d{8,17}\b/i',
            '/\bPolicy[:\s#]*[A-Z0-9]{6,20}\b/i',
            '/\bMember ID[:\s#]*[A-Z0-9]{6,20}\b/i',
            '/\bInsurance ID[:\s#]*[A-Z0-9]{6,20}\b/i',
            '/\bGroup[:\s#]*\d{5,12}\b/i',
        ],
        'addresses' => [
            '/\b\d{1,5}\s+[A-Za-z]+\s+(Street|St|Avenue|Ave|Boulevard|Blvd|Road|Rd|Drive|Dr|Lane|Ln|Court|Ct|Circle|Cir|Way|Place|Pl)\b\.?/i',
            '/\b(Apt|Suite|Unit|#)\s*\d+[A-Za-z]?\b/i',
            '/\bP\.?O\.?\s*Box\s*\d+\b/i',
        ],
        'county' => [
            '/\b[A-Z][a-z]+\s+County\b/i',
            '/\bCounty\s+of\s+[A-Z][a-z]+\b/i',
        ],
    ],
    'files' => [
        'common_names' => storage_path('app/phi/common_names.json'),
    ],
];
